version: '3.0'

expectations:
 population_size: 10000

actions:

  # create_dummy_openprompt_data: 
  #   run: >
  #     r:latest
  #       analysis/create_dummy_openprompt_data.R
  #   outputs: 
  #     moderately_sensitive: 
  #       dummy_openprompt: output/dummy_openprompt.csv.gz

  generate_openprompt_baseline: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/process_baseline.py 
        --output output/openprompt_baseline.csv
        --
        --day=0
    outputs:
      highly_sensitive:
        openprompt_baseline: output/openprompt_baseline.csv

  generate_openprompt_survey1: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/process_research.py 
        --output output/openprompt_survey1.csv
        --
        --day=0
    outputs:
      highly_sensitive:
        openprompt_survey1: output/openprompt_survey1.csv

  generate_openprompt_survey2: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/process_research.py 
        --output output/openprompt_survey2.csv
        --
        --day=30
    outputs:
      highly_sensitive:
        openprompt_survey2: output/openprompt_survey2.csv

  generate_openprompt_survey3: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/process_research.py 
        --output output/openprompt_survey3.csv
        --
        --day=60
    outputs:
      highly_sensitive:
        openprompt_survey3: output/openprompt_survey3.csv

  generate_openprompt_survey4: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/process_research.py 
        --output output/openprompt_survey4.csv
        --
        --day=90
    outputs:
      highly_sensitive:
        openprompt_survey4: output/openprompt_survey4.csv

  combine_openprompt:
    run: >
      r:latest analysis/001_datacombine.R
    needs: [generate_openprompt_baseline, generate_openprompt_survey1, generate_openprompt_survey2, generate_openprompt_survey3, generate_openprompt_survey4]
    outputs: 
      highly_sensitive: 
        openprompt_combined: output/openprompt_raw.gz.parquet
      moderately_sensitive:
        openprompt_raw_skim: output/data_properties/op_raw_skim.txt
        openprompt_raw_tab: output/data_properties/op_raw_tabulate.txt
        openprompt_mapped_skim: output/data_properties/op_mapped_skim.txt
        openprompt_mapped_tab: output/data_properties/op_mapped_tabulate.txt
        check_days_after_baseline: output/data_properties/sample_day_lags.pdf
        table1: output/tab1_baseline_description.html

  # generate_openprompt_plus_tpp: 
  #   run: >
  #     databuilder:v0
  #       generate-dataset analysis/dataset_definition_openprompt.py --output output/openprompt_raw_plus_tpp.csv.gz
  #   needs: [create_dummy_openprompt_data]
  #   outputs:
  #     highly_sensitive:
  #       openprompt_tpp_combined: output/openprompt_raw_plus_tpp.csv.gz

  # quick_summ_data:
  #   run: >
  #     r:latest
  #       analysis/010_table1.R
  #   needs: [generate_openprompt_plus_tpp]
  #   outputs:
  #     highly_sensitive:
  #       cleandata: output/cleaned_data.gz.parquet
  #     moderately_sensitive:
  #       table1: output/tab1_baseline_description.html
  #       longcovid_dates: output/longcovid_dates.pdf