version: '3.0'

expectations:
 population_size: 10000

actions:

  # create_dummy_openprompt_data: 
  #   run: >
  #     r:latest
  #       analysis/create_dummy_openprompt_data.R
  #   outputs: 
  #     moderately_sensitive: 
  #       dummy_openprompt: output/dummy_openprompt.csv

  generate_openprompt_baseline: 
    run: >
      databuilder:v0
        generate-dataset analysis/define_openprompt_baseline.py --output output/openprompt_baseline.csv
    outputs:
      highly_sensitive:
        openprompt_baseline: output/openprompt_baseline.csv

  generate_openprompt_survey1: 
    run: >
      databuilder:v0
        generate-dataset analysis/define_openprompt_survey1.py --output output/openprompt_survey1.csv
    outputs:
      highly_sensitive:
        openprompt_tpp_combined: output/openprompt_survey1.csv

  generate_openprompt_survey2: 
    run: >
      databuilder:v0
        generate-dataset analysis/define_openprompt_survey2.py --output output/openprompt_survey2.csv
    outputs:
      highly_sensitive:
        openprompt_tpp_combined: output/openprompt_survey2.csv

  combine_openprompt:
    run: >
      r:latest analysis/001_datacombine.R
    needs: [generate_openprompt_baseline, generate_openprompt_survey1, generate_openprompt_survey2]
    outputs: 
      highly_sensitive: 
        openprompt_combined: output/openprompt_raw.csv
        
  # generate_openprompt_plus_tpp: 
  #   run: >
  #     databuilder:v0
  #       generate-dataset analysis/dataset_definition_openprompt.py --output output/openprompt_raw_plus_tpp.gz.csv
  #   needs: [create_dummy_openprompt_data]
  #   outputs:
  #     highly_sensitive:
  #       openprompt_tpp_combined: output/openprompt_raw_plus_tpp.gz.csv

  # quick_summ_data:
  #   run: >
  #     r:latest
  #       analysis/010_table1.R
  #   needs: [generate_openprompt_plus_tpp]
  #   outputs:
  #     highly_sensitive:
  #       cleandata: output/cleaned_data.gz.parquet
  #     moderately_sensitive:
  #       table1: output/tab1_baseline_description.html
  #       longcovid_dates: output/longcovid_dates.pdf