version: '3.0'

expectations:
 population_size: 10000

actions:

  create_dummy_data: 
    run: >
      ehrql:v0
        create-dummy-tables 
        analysis/model_questions/dataset_definition.py output/dummydata 
        -- 
        --day=0
    outputs: 
      highly_sensitive:
        openprompt_dummy: output/dummydata/open_prompt.csv

  edit_dummy_data:
    run: > 
      r:latest
        analysis/dummy_data_editing/edit_automatic_dummy_data.R
    needs: [create_dummy_data]
    outputs: 
      highly_sensitive: 
        openprompt_dummy_edited: output/dummydata/dummy_edited/open_prompt.csv

  generate_openprompt_survey1: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/dataset_definition.py 
        --output output/openprompt_survey1.csv
        --dummy-tables output/dummydata/dummy_edited
        --
        --day=0
        --window=5
    needs: [edit_dummy_data]
    outputs:
      highly_sensitive:
        openprompt_survey1: output/openprompt_survey1.csv

  generate_openprompt_survey2: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/dataset_definition.py 
        --output output/openprompt_survey2.csv
        --dummy-tables output/dummydata/dummy_edited
        --
        --day=30
        --window=5
    needs: [edit_dummy_data]
    outputs:
      highly_sensitive:
        openprompt_survey2: output/openprompt_survey2.csv

  generate_openprompt_survey3: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/dataset_definition.py 
        --output output/openprompt_survey3.csv
        --dummy-tables output/dummydata/dummy_edited
        --
        --day=60
        --window=5
    needs: [edit_dummy_data]
    outputs:
      highly_sensitive:
        openprompt_survey3: output/openprompt_survey3.csv

  generate_openprompt_survey4: 
    run: >
      databuilder:v0
        generate-dataset 
        analysis/model_questions/dataset_definition.py 
        --output output/openprompt_survey4.csv
        --dummy-tables output/dummydata/dummy_edited
        --
        --day=90
        --window=5
    needs: [edit_dummy_data]
    outputs:
      highly_sensitive:
        openprompt_survey4: output/openprompt_survey4.csv

  combine_openprompt:
    run: >
      r:latest analysis/001_datacombine.R
    needs: [generate_openprompt_survey1, generate_openprompt_survey2, generate_openprompt_survey3, generate_openprompt_survey4]
    outputs: 
      highly_sensitive: 
        openprompt_combined: output/openprompt_raw.csv.gz
        openprompt_combined_stata: output/op_stata.dta
      moderately_sensitive:
        openprompt_raw_skim: output/data_properties/op_raw_skim.txt
        openprompt_raw_tab: output/data_properties/op_raw_tabulate.txt
        openprompt_mapped_skim: output/data_properties/op_mapped_skim.txt
        openprompt_mapped_tab: output/data_properties/op_mapped_tabulate.txt
        check_days_after_baseline: output/data_properties/sample_day_lags.pdf
        indexdates: output/data_properties/index_dates.pdf
        table1: output/tab1_baseline_description.html
        raw_summ_base_s: output/data_properties/op_baseline_skim.txt
        raw_summ_base_t: output/data_properties/op_baseline_tabulate.txt
        raw_summ_survey1_s: output/data_properties/op_survey1_skim.txt
        raw_summ_survey1_t: output/data_properties/op_survey1_tabulate.txt
        raw_summ_survey2_s: output/data_properties/op_survey2_skim.txt
        raw_summ_survey2_t: output/data_properties/op_survey2_tabulate.txt
        raw_summ_survey3_s: output/data_properties/op_survey3_skim.txt
        raw_summ_survey3_t: output/data_properties/op_survey3_tabulate.txt
        raw_summ_survey4_s: output/data_properties/op_survey4_skim.txt
        raw_summ_survey4_t: output/data_properties/op_survey4_tabulate.txt
        survey_date_consistency: output/data_properties/survey_date_consistency.csv
        survey_date_consistency_summary: output/data_properties/survey_date_consistency_summary.csv

  generate_openprompt_dataset:
    run: >
      stata-mp:latest analysis/op_combined.do
    needs: [combine_openprompt]
    outputs:
      highly_sensitive:
        data: output/openprompt_dataset.dta
        log: output/open-prompt-combine.log
   
  # gen_baseline_tables:
  #   run: >
  #     stata-mp:latest analysis/op_table1.do
  #   needs: [generate_openprompt_dataset]
  #   outputs:
  #     moderately_sensitive:
  #       demographic_data: output/tables/table1_demographic.csv
  #       questionnaire_data: output/tables/table1_questions.csv
  #       utility_score: output/figures/baseline_EQ5D_utility.svg
  #       disutility_score: output/figures/baseline_EQ5D_disutility.svg
  #       question_responses: output/figures/baseline_EQ5D_responses.svg
  #       question_percents: output/figures/baseline_EQ5D_percentage.svg
  #       vas_ncovids: output/figures/VAS_by_covids.svg
  #       vas_nvaccines: output/figures/VAS_by_vaccines.svg
  #       facit_fscore: output/figures/facit_baseline.svg
  #       log_tables: output/op-baseline-table1.log
